language: php
sudo: false
php:
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer require phpunit/phpunit

script: 
  - vendor/bin/phpunit tests/
