language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 5.6
    - php: 7.0

before_script:
  - composer self-update
  - composer require phpunit/phpunit

script:
  - vendor/bin/phpunit tests/
